import type { WebsiteSpec } from "./types";

export const restaurantModernV2FixtureSpec: WebsiteSpec = {
  version: "builder.v1",
  template: "restaurant-modern",
  palette: "ink-cream",
  business: {
    name: "Mariposa Comedor",
    industry: "Restaurant",
    city: "Coconut Creek",
    region: "Coconut Creek, FL",
    address: "123 Sample Road, Coconut Creek, FL",
    phone: "(954) 555-0195",
    email: null,
    websiteUrl: null,
    rating: 4.5,
    reviewCount: 295,
    description:
      "Salvadoran restaurant with pupusas, breakfast plates, soups, seafood, and casual counter-service dining.",
    cuisine: "Salvadoran restaurant",
    hours: null,
    dailyHours: [
      { day: "monday", label: "Monday", value: "8:00 AM - 10:00 PM", closed: false },
      { day: "tuesday", label: "Tuesday", value: "8:00 AM - 10:00 PM", closed: false },
      { day: "wednesday", label: "Wednesday", value: "8:00 AM - 10:00 PM", closed: false },
      { day: "thursday", label: "Thursday", value: "8:00 AM - 11:00 PM", closed: false },
      { day: "friday", label: "Friday", value: "8:00 AM - 11:00 PM", closed: false },
      { day: "saturday", label: "Saturday", value: "8:00 AM - 11:00 PM", closed: false },
      { day: "sunday", label: "Sunday", value: "Closed", closed: true },
    ],
    socialUrl: null,
    socialProfiles: [
      {
        platform: "instagram",
        url: "https://www.instagram.com/mariposa.comedor",
        sourceUrl: "https://public.example.test/mariposa-profile",
        verificationStatus: "operator_verified",
      },
      {
        platform: "facebook",
        url: "https://www.facebook.com/mariposa.comedor",
        sourceUrl: "https://public.example.test/mariposa-profile",
        verificationStatus: "operator_verified",
      },
      {
        platform: "youtube",
        url: "https://www.youtube.com/@mariposacomedor",
        sourceUrl: "https://public.example.test/mariposa-profile",
        verificationStatus: "operator_verified",
      },
    ],
    menuUrl: "https://public.example.test/mariposa-comedor-menu",
    orderUrl: null,
    reservationUrl: null,
    ratingSource: "public",
    shortName: "Mariposa Comedor",
    highlights: ["Salvadoran restaurant", "Pupusas", "Soups", "Seafood"],
  },
  assets: {
    images: [
      {
        url: "/fixtures/restaurant/market-table.svg",
        alt: "Colorful restaurant table with plates",
        role: "hero",
        sourceType: "operator_uploaded",
        sourceUrl: null,
        rightsStatus: "approved",
        approvalStatus: "approved",
        attribution: null,
      },
      {
        url: "/fixtures/restaurant/griddle.svg",
        alt: "Round masa cakes on a cooktop",
        role: "gallery",
        sourceType: "operator_uploaded",
        sourceUrl: null,
        rightsStatus: "approved",
        approvalStatus: "approved",
        attribution: null,
      },
      {
        url: "/fixtures/restaurant/dining-room.svg",
        alt: "Warm small dining room",
        role: "gallery",
        sourceType: "operator_uploaded",
        sourceUrl: null,
        rightsStatus: "approved",
        approvalStatus: "approved",
        attribution: null,
      },
      {
        url: "/fixtures/restaurant/plates.svg",
        alt: "Assorted colorful restaurant plates",
        role: "gallery",
        sourceType: "operator_uploaded",
        sourceUrl: null,
        rightsStatus: "approved",
        approvalStatus: "approved",
        attribution: null,
      },
    ],
  },
  navigation: [
    { id: "home", label: "Home" },
    { id: "menu", label: "Menu" },
    { id: "about", label: "About" },
    { id: "contact", label: "Visit" },
  ],
  pages: [
    {
      id: "home",
      path: "/",
      title: "Mariposa Comedor | Salvadoran restaurant in Coconut Creek",
      description: "Salvadoran restaurant in Coconut Creek, FL.",
      sections: [
        {
          type: "hero",
          eyebrow: "Salvadoran restaurant - Coconut Creek",
          headline: "Mariposa Comedor",
          lede:
            "Salvadoran restaurant with pupusas, breakfast plates, soups, seafood, and casual counter-service dining.",
          ctas: [
            { kind: "phone", label: "Call (954) 555-0195", href: "tel:9545550195" },
            { kind: "menu", label: "View menu", href: "https://public.example.test/mariposa-comedor-menu" },
          ],
        },
      ],
    },
  ],
  seo: {
    title: "Mariposa Comedor | Salvadoran restaurant in Coconut Creek",
    description: "Salvadoran restaurant in Coconut Creek, FL.",
  },
  auditFixes: [{ findingCode: "new_website_opportunity", addressed: true, builderAction: "create_internal_draft" }],
  provenance: [
    { field: "websiteStatus", provenance: "sourced", source: "lead.inspection_summary.no_standalone_website" },
    { field: "images", provenance: "sourced", source: "lead.inspection_summary.approved_images" },
    {
      field: "restaurantHighlights",
      provenance: "derived",
      source: "verified_public_facts.description+cuisine",
    },
  ],
};
